_target_: tsfm.model.decoder.TransformerDecoderPretrain
module_kwargs:
  _target_: builtins.dict
  distr_output:
    _target_: tsfm.distribution.MixtureOutput
    components:
      - _target_: tsfm.distribution.StudentTOutput
      - _target_: tsfm.distribution.StudentTOutput
      - _target_: tsfm.distribution.StudentTOutput
      - _target_: tsfm.distribution.StudentTOutput
  d_model: 256
  num_layers: 6
  patch_size: 32
  max_seq_len: 512
  attn_dropout_p: 0.0
  dropout_p: 0.0
  scaling: true
min_patches: 2
min_mask_ratio: 0.15
max_mask_ratio: 0.5
max_dim: 1
loss_func:
  _target_: tsfm.loss.packed.PackedNLLLoss
lr: 1e-3
weight_decay: 1e-1
beta1: 0.9
beta2: 0.98
num_training_steps: ${mul:${trainer.max_epochs},${train_dataloader.num_batches_per_epoch}}
num_warmup_steps: 10_000