name: aurora
channels:
  - pytorch
  - nvidia
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - pip=24.3.1
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - numpy=2.1.3
  - scipy=1.14.1
  - einops=0.8.0
  - timm=1.0.11
  - huggingface_hub=0.26.3
  - xarray=2024.11.0
  - numcodecs=0.13.1
  - cdsapi=0.7.5
  - netcdf4=1.7.2
  - dask=2024.12.0
  - zarr=2.18.3
  - metpy=1.6.3
  - hydra-core=1.3.2
  - wandb==0.19.0
  - pip:
      - -e .
