defaults:
  - cluster: cleps
  - dataloader: era5
  - module: forecast
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

log: True # wandb logging False True

name: ${module.name}
project: ${module.project}
exp_dir: ${cluster.wandb_dir}${module.project}/${name}/test/ # ${cluster.wandb_dir}${module.project}/${name}/3x3090_save_loss/ # /mnt/cache/data/zi/archesmodels/

max_steps: 320000
#max_steps: 2000
batch_size: ${cluster.batch_size}
resume: False

save_step_frequency: 20000 # 3000 50000 6000
log_freq: 100
limit_val_batches: 6
debug: False # set to True to debug