# Common attributes for all tasks
task: "train"  # Can be "train" or "forecast"
model_name: "AuroraSmall"  # Change this to "AuroraSmall" or "Aurora" as needed
distributed: False
use_activation_checkpointing: True
use_torch_compile: False  # Turn on for faster training, but initialization is slower

# Attributes for training task
phase: "rollout_long_buffer" # Can be "pretraining", "finetuning", "rollout_short", "rollout_long_buffer", "rollout_long"
total_steps: 200
rollout_steps: 1
buffer_size: 200
refresh_freq: 10
